-- SCRIPT DEFINITIVO



-- DUBBI:
-- AGGIUNTA DI ATTRIBUTO "MEETING POINT" PER ASSIGNMENT
-- DUPLICAZIONE ATTRIBUTI SU JOIN

USE CANIBAU;

DROP TABLE IF EXISTS MEETING_POINT;
DROP TABLE IF EXISTS DOG_ASSIGNMENT;
DROP TABLE IF EXISTS ASSIGNMENT;
DROP TABLE IF EXISTS DOGS;
DROP TABLE IF EXISTS DOGS_ACCEPTED;
DROP TABLE IF EXISTS BREEDS;
DROP TABLE IF EXISTS DOGSITTER_AREA;
DROP TABLE IF EXISTS PRICE_LIST;
DROP TABLE IF EXISTS REVIEW;
DROP TABLE IF EXISTS AVAILABILITY;
DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS DOGSITTERS;
DROP TABLE IF EXISTS ADDRESS;
DROP TABLE IF EXISTS CREDIT_CARDS;






CREATE TABLE CREDIT_CARDS
					(NUM CHAR(17) PRIMARY KEY,
					OWNER_NAME CHAR(20),
					OWNER_SURNAME CHAR(20),
					EXPIRATION_DATE DATE,
					CVV SMALLINT,
                    AMOUNT DOUBLE)

                    ENGINE = INNODB;

CREATE TABLE PRICE_LIST
					(SIZE CHAR(15) PRIMARY KEY,
					PRICE DOUBLE)


                    ENGINE = INNODB;

CREATE TABLE ADDRESS
						(EMAIL CHAR(254) PRIMARY KEY,
						COUNTRY CHAR(30),
						CITY CHAR(50),
						STREET CHAR(50),
						CNUMBER CHAR(10),
						CAP CHAR(10))

                        -- FOREIGN KEY(EMAIL) REFERENCES CUSTOMERS(EMAIL),
                        -- FOREIGN KEY(EMAIL) REFERENCES DOGSITTERS(EMAIL))
                        ENGINE = INNODB;

CREATE TABLE CUSTOMERS
						(EMAIL CHAR(255) PRIMARY KEY,
						NAME CHAR(15),
                        SURNAME CHAR(15),
                        PASSWORD CHAR(20),
                        PHONE_NUMB BIGINT,
                        BIRTHDATE DATE,
                        PAYMENT CHAR(17),

                        FOREIGN KEY(EMAIL) REFERENCES ADDRESS(EMAIL),
                        FOREIGN KEY(PAYMENT) REFERENCES CREDIT_CARDS(NUM))
                        ENGINE = INNODB;


CREATE TABLE DOGSITTERS
					(EMAIL CHAR(254) PRIMARY KEY,
					NAME CHAR(45),
					SURNAME CHAR(45),
					PASSWORD CHAR(45) ,
					PHONE_NUMB BIGINT,
					BIRTHDATE DATE,
					PAYMENT CHAR(17),
					CASH_FLAG BOOLEAN,
					AREA CHAR(45),
					BIOGRAPHY TEXT,

                    FOREIGN KEY(EMAIL) REFERENCES ADDRESS(EMAIL),
					FOREIGN KEY (PAYMENT) REFERENCES CREDIT_CARDS(NUM))
                    ENGINE = INNODB;







CREATE TABLE BREEDS
					(NAME CHAR(45) PRIMARY KEY,
					 SIZE CHAR(15),

                     FOREIGN KEY (SIZE) REFERENCES PRICE_LIST(SIZE))
                     ENGINE = INNODB;



CREATE TABLE DOGS
					(ID INT PRIMARY KEY,
					NAME CHAR(20),
					BREED  CHAR(45),
					WEIGHT DOUBLE,
					AGE INT,
					OWNER_EMAIL CHAR(254),

                    FOREIGN KEY(OWNER_EMAIL) REFERENCES CUSTOMERS(EMAIL),
                    FOREIGN KEY(BREED) REFERENCES BREEDS(NAME))
                    ENGINE = INNODB;




CREATE TABLE ASSIGNMENT
					(CODE CHAR(254) PRIMARY KEY,
                    CUSTOMER CHAR(254),
                    DOGSITTER CHAR(254),
                    CONFIRMATION BOOLEAN,
                    DATE_START DATETIME,
                    DATE_END DATETIME)

                    ENGINE = INNODB;


CREATE TABLE DOG_ASSIGNMENT
					(CODE CHAR(254),
                    DOG_ID INT,

                    PRIMARY KEY (CODE, DOG_ID),
                    FOREIGN KEY (CODE) REFERENCES ASSIGNMENT(CODE),
                    FOREIGN KEY (DOG_ID) REFERENCES DOGS(ID))
                    ENGINE = INNODB;


CREATE TABLE REVIEW
					(CUSTOMER CHAR(254),
					DOGSITTER CHAR(254),
					DATE DATETIME,
                    RATING INT,
					TITLE CHAR(254),
                    DESCRIPTION TEXT,
                    REPLY TEXT,

                    PRIMARY KEY (CUSTOMER, DOGSITTER, DATE),
                    FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMERS(EMAIL),
                    FOREIGN KEY (DOGSITTER) REFERENCES DOGSITTERS(EMAIL))
                    ENGINE = INNODB;


CREATE TABLE DOGSITTER_AREA
					(DOGSITTER CHAR (254),
                    CITY CHAR(50),

                    PRIMARY KEY (DOGSITTER, CITY),
                    FOREIGN KEY (DOGSITTER) REFERENCES DOGSITTERS(EMAIL))
                    ENGINE = INNODB;


CREATE TABLE DOGS_ACCEPTED
					(DOGSITTER CHAR(254) PRIMARY KEY,
                    SMALL BOOLEAN,
                    MEDIUM BOOLEAN,
                    LARGE BOOLEAN,
                    EXTRA_LARGE BOOLEAN,

                    FOREIGN KEY(DOGSITTER) REFERENCES DOGSITTERS(EMAIL))
                    ENGINE = INNODB;


CREATE TABLE MEETING_POINT
					(CODE CHAR(254) PRIMARY KEY,
					COUNTRY CHAR(30),
					CITY CHAR(50),
					STREET CHAR(50),
					CNUMBER CHAR(10),
					CAP CHAR(10),

                    FOREIGN KEY(CODE) REFERENCES ASSIGNMENT(CODE))
                    ENGINE = INNODB;


CREATE TABLE AVAILABILITY
					(DOGSITTER CHAR(254) PRIMARY KEY,
                    MON_START TIME,
                    MON_END TIME,
                    TUE_START TIME,
                    TUE_END TIME,
                    WED_START TIME,
                    WED_END TIME,
                    THU_START TIME,
                    THU_END TIME,
                    FRI_START TIME,
                    FRI_END TIME,
                    SAT_START TIME,
                    SAT_END TIME,
                    SUN_START TIME,
                    SUN_END TIME,

                    FOREIGN KEY (DOGSITTER) REFERENCES DOGSITTERS(EMAIL))
                    ENGINE = INNODB;







INSERT INTO PRICE_LIST (PRICE, SIZE) VALUES (5,'SMALL');
INSERT INTO PRICE_LIST (PRICE, SIZE) VALUES (10,'MEDIUM');
INSERT INTO PRICE_LIST (PRICE, SIZE) VALUES (15,'LARGE');
INSERT INTO PRICE_LIST (PRICE, SIZE) VALUES (20,'EXTRA LARGE');


INSERT INTO BREEDS VALUES ('BEAGLE','MEDIUM');
INSERT INTO BREEDS VALUES ('BOXER','LARGE');
INSERT INTO BREEDS VALUES ('BULLDOG','LARGE');
INSERT INTO BREEDS VALUES ('CHIHUAHUA','SMALL');
INSERT INTO BREEDS VALUES ('DACHSHUND','SMALL');
INSERT INTO BREEDS VALUES ('GERMAN SHEPHERD DOG','LARGE');
INSERT INTO BREEDS VALUES ('GOLDEN RETRIEVER','LARGE');
INSERT INTO BREEDS VALUES ('LABRADOR RETRIEVER','LARGE');
INSERT INTO BREEDS VALUES ('MINIATURE POODLE','SMALL');
INSERT INTO BREEDS VALUES ('MINIATURE SCHNAUZER','SMALL');
INSERT INTO BREEDS VALUES ('SHIH TZU','SMALL');
INSERT INTO BREEDS VALUES ('STANDARD POODLE','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('TOY POODLE','SMALL');
INSERT INTO BREEDS VALUES ('YORKSHIRE TERRIER','SMALL');
INSERT INTO BREEDS VALUES ('BOSTON TERRIER','SMALL');
INSERT INTO BREEDS VALUES ('BRITTANY','MEDIUM');
INSERT INTO BREEDS VALUES ('CAVALIER KING CHARLES SPANIEL','SMALL');
INSERT INTO BREEDS VALUES ('COCKER SPANIEL','MEDIUM');
INSERT INTO BREEDS VALUES ('DOBERMAN PINSCHER','LARGE');
INSERT INTO BREEDS VALUES ('ENGLISH SPRINGER SPANIEL','LARGE');
INSERT INTO BREEDS VALUES ('GERMAN SHORTHAIRED POINTER','LARGE');
INSERT INTO BREEDS VALUES ('GREAT DANE','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('MALTESE','SMALL');
INSERT INTO BREEDS VALUES ('MASTIFF','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('MINIATURE PINSCHER','SMALL');
INSERT INTO BREEDS VALUES ('PEMBROKE WELSH CORGI','MEDIUM');
INSERT INTO BREEDS VALUES ('POMERANIAN','SMALL');
INSERT INTO BREEDS VALUES ('PUG','SMALL');
INSERT INTO BREEDS VALUES ('ROTTWEILER','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('SHETLAND SHEEPDOG','SMALL');
INSERT INTO BREEDS VALUES ('SIBERIAN HUSKY','MEDIUM');
INSERT INTO BREEDS VALUES ('AUSTRALIAN SHEPHERD','LARGE');
INSERT INTO BREEDS VALUES ('BASSET HOUND','LARGE');
INSERT INTO BREEDS VALUES ('BERNESE MOUNTAIN DOG','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('BICHON FRISE','SMALL');
INSERT INTO BREEDS VALUES ('BLOODHOUND','LARGE');
INSERT INTO BREEDS VALUES ('BULLMASTIFF','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('COLLIE','LARGE');
INSERT INTO BREEDS VALUES ('FRENCH BULLDOG','MEDIUM');
INSERT INTO BREEDS VALUES ('HAVANESE','SMALL');
INSERT INTO BREEDS VALUES ('NEWFOUNDLAND','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('PAPILLON','SMALL');
INSERT INTO BREEDS VALUES ('SAINT BERNARD','EXTRA LARGE');
INSERT INTO BREEDS VALUES ('VIZSLA','LARGE');
INSERT INTO BREEDS VALUES ('WEIMARANER','LARGE');
INSERT INTO BREEDS VALUES ('WEST HIGHLAND WHITE TERRIER','SMALL');
INSERT INTO BREEDS VALUES ('AIREDALE TERRIER','LARGE');
INSERT INTO BREEDS VALUES ('AKITA','LARGE');
INSERT INTO BREEDS VALUES ('ALASKAN MALAMUTE','LARGE');
INSERT INTO BREEDS VALUES ('BORDER COLLIE','MEDIUM');
INSERT INTO BREEDS VALUES ('SMALL HALF-BREED','SMALL');
INSERT INTO BREEDS VALUES ('MEDIUM HALF-BREED','MEDIUM');
INSERT INTO BREEDS VALUES ('LARGE HALF-BREED','LARGE');
INSERT INTO BREEDS VALUES ('EXTRA LARGE HALF-BREED','EXTRA LARGE');












